version: "3.8"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "3050:80"
    depends_on:
      - client
      - api
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
      platforms:
        - linux/arm64
        - linux/amd64
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_PROTOCOL=http
      - REACT_APP_HOSTNAME=localhost
      - REACT_APP_PORT=:8000/api

  api:
    build:
      dockerfile: Dockerfile
      context: ./server
      platforms:
        - linux/arm64
        - linux/amd64
    ports: 
      - "8000:8000"
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - ALGORITHM=HS256
      - SECRET_KEY=87b113dede1fdbe718c21ae6055a023d64b3e926f74e329523087b15736c0027
      - ACCESS_TOKEN_EXPIRE_MINUTES=240
  emr-postgres:
    image: postgres:latest
    platform: linux/amd64
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
